# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java



jobs:
  - job: TestJob
    displayName: "Test Job"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: echo "Running tests"
        displayName: 'Run Tests'