# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


trigger:
  - main

jobs:
  - job: BuildJob
    displayName: "Build Job"
    pool:
      name: WindowsAgentPools
    steps:
      - task: Maven@4
        inputs:
          mavenPomFile: 'MavenHelloWorld-master/pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'
          
  - job: TestJob
    displayName: "Test Job"
    pool:
      name: WindowsAgentPools
    steps:
      - script: echo "Running tests"
        displayName: 'Run Tests'